name: OHW-py
channels:
  - conda-forge
dependencies:
  - python=3
  - gh
  - argopy>=0.1.7
  - bokeh
  - bottleneck
  - cartopy
  - cf-units
  - cf_xarray
  - cmocean
  - colorcet
  - compilers
  - compliance-checker
  - conda-lock
  - ctd
  - datashader
  - echopype
  - erddapy
  - fastparquet
  - ffmpeg
  - fsspec
  - gcsfs
  - geopandas
  - geoviews
  - graphviz
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ioos_qc
  - ipyleaflet
  - ipywidgets
  - jupyter
  - matplotlib-base
  - movingpandas
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - python-snappy
  - rasterio
  - regionmask
  - requests
  - retrying
  - rise
  - s3fs
  - scipy
  - seaborn
  - searvey
  - seawater
  - shapely
  - siphon
  - xarray
  - xgcm
  - xlrd
  - zarr
